# Generated by Django 5.0 on 2023-12-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1', models.CharField(max_length=2)),
                ('card2', models.CharField(max_length=2)),
                ('card3', models.CharField(max_length=2)),
                ('card4', models.CharField(max_length=2)),
                ('card5', models.CharField(max_length=2)),
                ('card6', models.CharField(max_length=2)),
                ('card7', models.CharField(max_length=2)),
                ('card8', models.CharField(max_length=2)),
                ('card9', models.CharField(max_length=2)),
                ('card10', models.CharField(max_length=2)),
                ('card11', models.CharField(max_length=2)),
                ('card12', models.CharField(max_length=2)),
                ('card13', models.CharField(max_length=2)),
                ('card14', models.CharField(max_length=2)),
                ('card15', models.CharField(max_length=2)),
                ('card16', models.CharField(max_length=2)),
                ('card17', models.CharField(max_length=2)),
                ('card18', models.CharField(max_length=2)),
                ('card19', models.CharField(max_length=2)),
                ('card20', models.CharField(max_length=2)),
                ('card21', models.CharField(max_length=2)),
                ('card22', models.CharField(max_length=2)),
                ('card23', models.CharField(max_length=2)),
                ('card24', models.CharField(max_length=2)),
                ('card25', models.CharField(max_length=2)),
                ('card26', models.CharField(max_length=2)),
                ('card27', models.CharField(max_length=2)),
                ('card28', models.CharField(max_length=2)),
                ('card29', models.CharField(max_length=2)),
                ('card30', models.CharField(max_length=2)),
                ('card31', models.CharField(max_length=2)),
                ('card32', models.CharField(max_length=2)),
                ('card33', models.CharField(max_length=2)),
                ('card34', models.CharField(max_length=2)),
                ('card35', models.CharField(max_length=2)),
                ('card36', models.CharField(max_length=2)),
                ('card37', models.CharField(max_length=2)),
                ('card38', models.CharField(max_length=2)),
                ('card39', models.CharField(max_length=2)),
                ('card40', models.CharField(max_length=2)),
                ('card41', models.CharField(max_length=2)),
                ('card42', models.CharField(max_length=2)),
                ('card43', models.CharField(max_length=2)),
                ('card44', models.CharField(max_length=2)),
                ('car45', models.CharField(max_length=2)),
                ('card46', models.CharField(max_length=2)),
                ('card47', models.CharField(max_length=2)),
                ('card48', models.CharField(max_length=2)),
                ('card49', models.CharField(max_length=2)),
                ('card50', models.CharField(max_length=2)),
                ('card51', models.CharField(max_length=2)),
                ('card52', models.CharField(max_length=2)),
            ],
        ),
    ]
