# Generated by Django 5.0 on 2023-12-26 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='room',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.room'),
        ),
    ]
