# Generated by Django 5.0 on 2023-12-26 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_deck_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('stackSize', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='car45',
            new_name='card45',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='room',
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb', models.PositiveIntegerField()),
                ('bb', models.PositiveIntegerField()),
                ('buttonLocation', models.PositiveSmallIntegerField()),
                ('player1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='game.player')),
                ('player2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='game.player')),
                ('player3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='game.player')),
                ('player4', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='game.player')),
                ('player5', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='game.player')),
                ('player6', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='game.player')),
                ('player7', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='game.player')),
                ('player8', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='game.player')),
                ('room', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='table',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.table'),
        ),
    ]
