# Generated by Django 5.0 on 2023-12-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_rename_car45_deck_card45_remove_deck_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='buttonLocation',
            new_name='buttonPosition',
        ),
    ]
