# Generated by Django 5.0 on 2023-12-26 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_buttonlocation_table_buttonposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='player1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='game.player'),
        ),
        migrations.AlterField(
            model_name='table',
            name='player2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='game.player'),
        ),
        migrations.AlterField(
            model_name='table',
            name='player3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='game.player'),
        ),
        migrations.AlterField(
            model_name='table',
            name='player4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='game.player'),
        ),
        migrations.AlterField(
            model_name='table',
            name='player5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='game.player'),
        ),
        migrations.AlterField(
            model_name='table',
            name='player6',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='game.player'),
        ),
        migrations.AlterField(
            model_name='table',
            name='player7',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='game.player'),
        ),
        migrations.AlterField(
            model_name='table',
            name='player8',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='game.player'),
        ),
    ]
