# Generated by Django 5.0 on 2023-12-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_table_alter_table_player1_alter_table_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='betThisRound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='folded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='pot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='stage',
            field=models.CharField(default='preflop', max_length=8),
        ),
    ]
